name: alcig
description: A sample web application
dependencies:
  angular: ">=1.1.0 <2.0.0"
  browser: any
  intl: any
  web_components: any
dev_dependencies:
  unittest: any
  dart_to_js_script_rewriter: ^1.0.2
transformers:
- angular
- dart_to_js_script_rewriter
