name: alcig
description: A sample web application
dependencies:
  angular: ">=4.0.0 <5.0.0"
  angular_router: ">=1.0.0 <2.0.0"
  angular_forms: ">=1.0.0 <2.0.0"
  browser: any
  intl: any
dev_dependencies:
  unittest: any
  dart_to_js_script_rewriter: ^1.0.2
transformers:
- angular:
    entry_points:
    - web/index.dart
- dart_to_js_script_rewriter
